name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install black flake8 mypy pytest apache-airflow

      - name: Black check
        run: black --check dags tests

      - name: Flake8
        run: flake8 dags

      - name: MyPy
        run: mypy dags

  test:
    runs-on: ubuntu-latest
    needs: lint
    services:
      minio:
        image: minio/minio:latest
        ports: ['9000:9000']
        env:
          MINIO_ACCESS_KEY: minioadmin
          MINIO_SECRET_KEY: minioadmin
        options: >-
          --health-cmd "mc alias set local http://localhost:9000 minioadmin minioadmin && mc ls local"
          --health-interval 10s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest moto

      - name: Run pytest
        env:
          AIRFLOW__CORE__FERNET_KEY: 'dummy_fernet_key'
          AIRFLOW__CORE__DAGS_FOLDER: 'dags'
          AWS_ACCESS_KEY_ID: minioadmin
          AWS_SECRET_ACCESS_KEY: minioadmin
          AWS_ENDPOINT_URL: http://localhost:9000
        run: |
          pytest --maxfail=1 --disable-warnings -v
